// /*
//  * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//  * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
//  */
// package Phuc;

// import BLL.DN_BLL;
// import DTO.DonNhan_DTO;
// import DTO.SP_DTO;
// import java.util.ArrayList;
// import javax.swing.table.DefaultTableModel;

// /**
//  *
//  * @author Paul
//  */
// public class DonNhan extends javax.swing.JPanel {

//     /**
//      * Creates new form DonNhan1
//      */
//     private String madon, ngay, manv;
//     private int dot, total;
//     private static int i=0;
//     private DN_BLL dnbll;
//     private DonNhan_DTO dndto;
//     private ArrayList<SP_DTO>listsp=new ArrayList();
//     private Execute ex;
//     private static int dongia=0, sum=0;
//     public DonNhan() {
//         initComponents();
//     }

//     /**
//      * This method is called from within the constructor to initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is always
//      * regenerated by the Form Editor.
//      */
//     @SuppressWarnings("unchecked")
//     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//     private void initComponents() {

//         jScrollPane1 = new javax.swing.JScrollPane();
//         jTable1 = new javax.swing.JTable();
//         jLabel1 = new javax.swing.JLabel();
//         jLabel2 = new javax.swing.JLabel();
//         t1 = new javax.swing.JTextField();
//         jLabel3 = new javax.swing.JLabel();
//         t2 = new javax.swing.JTextField();
//         jLabel4 = new javax.swing.JLabel();
//         t3 = new javax.swing.JTextField();
//         jLabel5 = new javax.swing.JLabel();
//         t4 = new javax.swing.JTextField();
//         jLabel7 = new javax.swing.JLabel();
//         t6 = new javax.swing.JTextField();
//         add = new javax.swing.JButton();
//         clear = new javax.swing.JButton();
//         view = new javax.swing.JButton();
//         addrow = new javax.swing.JButton();
//         Clear = new javax.swing.JButton();
//         jScrollPane3 = new javax.swing.JScrollPane();
//         tb2 = new javax.swing.JTable();
//         calc = new javax.swing.JButton();

//         jTable1.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null, null},
//                 {null, null, null, null, null},
//                 {null, null, null, null, null},
//                 {null, null, null, null, null}
//             },
//             new String [] {
//                 "Mã đơn nhận", "Ngày nhận", "Đợt nhận", "Nhân viên nhận", "Tổng tiền"
//             }
//         ));
//         jScrollPane1.setViewportView(jTable1);

//         jLabel1.setText("Đơn nhận hàng");

//         jLabel2.setText("Mã đơn nhận");

//         jLabel3.setText("Ngày nhận");

//         jLabel4.setText("Đợt nhận");

//         jLabel5.setText("Mã nhân viên ");

//         jLabel7.setText("Tổng tiền");

//         add.setText("Thêm");
//         add.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 addActionPerformed(evt);
//             }
//         });

//         clear.setText("Làm mới");
//         clear.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 clearActionPerformed(evt);
//             }
//         });

//         view.setText("Xem");
//         view.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 viewActionPerformed(evt);
//             }
//         });

//         addrow.setText("Add Row");
//         addrow.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 addrowActionPerformed(evt);
//             }
//         });

//         Clear.setText("Clear");
//         Clear.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 ClearActionPerformed(evt);
//             }
//         });

//         tb2.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null}
//             },
//             new String [] {
//                 "MASP", "Tên SP", "Số lượng đặt", "Tổng tiền"
//             }
//         ));
//         jScrollPane3.setViewportView(tb2);

//         calc.setText("Calc");
//         calc.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 calcActionPerformed(evt);
//             }
//         });

//         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
//         this.setLayout(layout);
//         layout.setHorizontalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addGroup(layout.createSequentialGroup()
//                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                     .addGroup(layout.createSequentialGroup()
//                         .addGap(153, 153, 153)
//                         .addComponent(jLabel1)
//                         .addGap(0, 0, Short.MAX_VALUE))
//                     .addGroup(layout.createSequentialGroup()
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addComponent(jLabel3)
//                             .addComponent(jLabel4)
//                             .addComponent(jLabel5)
//                             .addComponent(jLabel7)
//                             .addComponent(jLabel2))
//                         .addGap(18, 18, 18)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(layout.createSequentialGroup()
//                                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                     .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
//                                     .addComponent(t4)
//                                     .addComponent(t6)
//                                     .addComponent(t2))
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                 .addComponent(calc))
//                             .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
//                         .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                     .addGroup(layout.createSequentialGroup()
//                         .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                             .addGroup(layout.createSequentialGroup()
//                                 .addComponent(add)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(clear)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(view)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(addrow)
//                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                 .addComponent(Clear)
//                                 .addGap(0, 0, Short.MAX_VALUE))
//                             .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
//                         .addContainerGap())))
//         );
//         layout.setVerticalGroup(
//             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//             .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
//             .addGroup(layout.createSequentialGroup()
//                 .addGap(29, 29, 29)
//                 .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
//                 .addGap(35, 35, 35)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel2)
//                     .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(23, 23, 23)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(jLabel3))
//                 .addGap(33, 33, 33)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel4)
//                     .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(29, 29, 29)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(jLabel5)
//                     .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(28, 28, 28)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                     .addComponent(jLabel7)
//                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                         .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                         .addComponent(calc)))
//                 .addGap(18, 18, 18)
//                 .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
//                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                     .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(addrow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
//                     .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
//                 .addGap(27, 27, 27))
//         );
//     }// </editor-fold>//GEN-END:initComponents

//     private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
//             madon = t1.getText();
//             ngay = t2.getText();
//             dot = Integer.parseInt(t3.getText());
//             manv = t4.getText();
//             total = Integer.parseInt(t6.getText());
//             dnbll=new DN_BLL();
//             dndto=new DonNhan_DTO(madon,ngay,dot,manv ,total);
//             for(int i=0;i<tb2.getRowCount();i++)
//             {
//                 if(tb2.isRowSelected(i)==true)           
//                 {  
//                     String a=String.valueOf(tb2.getValueAt(i,0));
//                     String b=String.valueOf(tb2.getValueAt(i,1));
//                     int c=Integer.parseInt(String.valueOf(tb2.getValueAt(i,2)));
//                     int d=Integer.parseInt(String.valueOf(tb2.getValueAt(i,3))); 
//                     SP_DTO sp=new SP_DTO(a,b,c,d);
//                     listsp.add(sp);
//                 }
//             }
//             dnbll.Add(dndto, listsp);  
//     }//GEN-LAST:event_addActionPerformed

//     private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
//        dnbll=new DN_BLL();
//             DefaultTableModel models = (DefaultTableModel)jTable1.getModel();
//             for(int i=0;i<dnbll.View().size();i++)
//             {        
//                 jTable1.setValueAt(dnbll.View().get(i).getMadn(), i, 0);
//                 jTable1.setValueAt(dnbll.View().get(i).getNgnhan(), i, 1);
//                 jTable1.setValueAt(dnbll.View().get(i).getDot(), i, 2);
//                 jTable1.setValueAt(dnbll.View().get(i).getManv(), i, 3);
//                 jTable1.setValueAt(dnbll.View().get(i).getTong(), i, 5);
//                 models.addRow(new Object[] {});
//             }  
//     }//GEN-LAST:event_viewActionPerformed

//     private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
//         t1.setText("");
//         t2.setText("");
//         t3.setText("");
//         t4.setText(""); 
//         t6.setText("");
//     }//GEN-LAST:event_clearActionPerformed

//     private void addrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrowActionPerformed
//        DefaultTableModel models = (DefaultTableModel)tb2.getModel();
//         models.addRow(new Object[] {});
//     }//GEN-LAST:event_addrowActionPerformed

//     private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
//         t1.setText("");
//         t2.setText("");
//         t3.setText("");
//         t4.setText("");
//         t6.setText("");
//         for(int i=0;i<tb2.getRowCount();i++)
//         {
//             if(tb2.isRowSelected(i))
//             {
//                  tb2.setValueAt("", i, 0);
//                  tb2.setValueAt("", i, 1);
//                  tb2.setValueAt("", i, 2);
//                  tb2.setValueAt("", i, 3);
//             }
//         }
//     }//GEN-LAST:event_ClearActionPerformed

//     private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
//         try
//         {
//             ex=new Execute();
//             double sl;
//             for(int i=0;i<tb2.getRowCount();i++)
//             {
//                 if(tb2.isRowSelected(i)==true)
//                 {
//                     sl=Double.parseDouble(String.valueOf(tb2.getValueAt(i, 2)));         
//                     dongia=Integer.parseInt(String.valueOf(tb2.getValueAt(i, 3)));
//                     sum+=ex.Res(sl,dongia);     
//                     t6.setText(String.valueOf(sum));
//                 }
//             } 
//         }catch(NumberFormatException ne){
//             System.out.println(ne);
//         }
//     }//GEN-LAST:event_calcActionPerformed


//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton Clear;
//     private javax.swing.JButton add;
//     private javax.swing.JButton addrow;
//     private javax.swing.JButton calc;
//     private javax.swing.JButton clear;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JLabel jLabel2;
//     private javax.swing.JLabel jLabel3;
//     private javax.swing.JLabel jLabel4;
//     private javax.swing.JLabel jLabel5;
//     private javax.swing.JLabel jLabel7;
//     private javax.swing.JScrollPane jScrollPane1;
//     private javax.swing.JScrollPane jScrollPane3;
//     private javax.swing.JTable jTable1;
//     private javax.swing.JTextField t1;
//     private javax.swing.JTextField t2;
//     private javax.swing.JTextField t3;
//     private javax.swing.JTextField t4;
//     private javax.swing.JTextField t6;
//     private javax.swing.JTable tb2;
//     private javax.swing.JButton view;
//     // End of variables declaration//GEN-END:variables
// }
