/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Phuc;

import BLL.TKHH_BLL;
import GUI.Items.ButtonCustomed;

import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul
 */
public class ThongKeHang extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeHang
     */
    private TKHH_BLL tkhhbll;
    private String masearch;   
    public ThongKeHang() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable() {
            @Override
            public boolean editCellAt(int row, int column) {
                return false;
            };

            @Override
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            };
        };
        jTable1.getTableHeader().setReorderingAllowed(false);
        
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        search = new ButtonCustomed();
        bt1 = new ButtonCustomed();
        bt2 = new ButtonCustomed();

        
        bt1.setBackground(new ColorUIResource(116, 47, 158));
        bt2.setBackground(new ColorUIResource(116, 47, 158));
        search.setBackground(new ColorUIResource(116, 47, 158));

        bt1.setColorHover(new ColorUIResource(181, 113, 209));
        bt2.setColorHover(new ColorUIResource(181, 113, 209));
        search.setColorHover(new ColorUIResource(181, 113, 209));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Loại", "Số lượng đã bán", "Còn tồn"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("");


        jLabel2.setText("Nhập MASP");

        search.setText("Tìm Kiếm");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        bt1.setText("Thống kê");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setText("Làm mới");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(bt1)
                        .addGap(61, 61, 61)
                        .addComponent(bt2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt2))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
            tkhhbll=new TKHH_BLL();
            masearch = txt.getText();           
            jTable1.setValueAt(tkhhbll.Search(masearch).getMASP(), 0,0);
            jTable1.setValueAt(tkhhbll.Search(masearch).getTen(), 0,1);
            jTable1.setValueAt(tkhhbll.Search(masearch).getLoai(),0,2);
            jTable1.setValueAt(tkhhbll.Search(masearch).getSL(), 0,3);
            jTable1.setValueAt(tkhhbll.Search(masearch).getConLai(),0,4); 
        
    }//GEN-LAST:event_searchActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        tkhhbll=new TKHH_BLL();
            DefaultTableModel models = (DefaultTableModel)jTable1.getModel();
            for(int i=0;i<tkhhbll.Statistic().size();i++)
            {
                jTable1.setValueAt(tkhhbll.Statistic().get(i).getMASP(), i,0);
                jTable1.setValueAt(tkhhbll.Statistic().get(i).getTen(), i,1);
                jTable1.setValueAt(tkhhbll.Statistic().get(i).getLoai(), i,2);
                jTable1.setValueAt(tkhhbll.Statistic().get(i).getSL(), i,3);
                jTable1.setValueAt(tkhhbll.Statistic().get(i).getConLai(), i,4);
                models.addRow(new Object[] {});
            }   
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            if(jTable1.isRowSelected(i))
            {
                 jTable1.setValueAt("", i, 0);
                 jTable1.setValueAt("", i, 1);
                 jTable1.setValueAt("", i, 2);
                 jTable1.setValueAt("", i, 3);
                 jTable1.setValueAt("", i, 4);
            }
        }
    }//GEN-LAST:event_bt2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonCustomed bt1;
    private ButtonCustomed bt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private ButtonCustomed search;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
